name: tap-task-action
description: 'Sets up the keg-cli and your tap, then runs a task'

branding:
  icon: 'terminal'
  color: 'red'

inputs:
  cli_git_branch:
    description: 'keg-cli branch to use during execution'
    default: 'develop'
  keg_hub_git_branch:
    description: 'keg-hub branch to use during execution'
    default: 'develop'
  tap_ref:
    description: >
      For PUSH events, the tap ref to checkout (example: /ref/heads/my-feature-branch). When checking out the repository that
      triggered a workflow, this defaults to the reference or SHA for that
      event. 
    default: ${{ github.ref }}
  tap_head_ref:
    description: >
      For PULL_REQUEST events, the tap branch to checkout (example: /ref/heads/my-feature-branch). When checking out the repository that
      triggered a workflow, this defaults to the reference or SHA for that
      event. `tap-task-action` will try to use this before falling back to `tap_ref`
    default: ${{ github.head_ref }}
  tap_alias:
    description: The link alias for your tap. If omitted, the task will look for an alias in your your tap's config file (e.g tap.js(on))
  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    default: ${{ github.repository }}
  command:
    description: 'The command to run once the keg-cli and your tap are setup'
    required: true
  token:
    description: >
      Personal access token (PAT) used to fetch the repository and push its image. 
      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.
    default: ${{ github.token }}
  user:
    description: 'The username for docker login'
    default: 'keg-admin'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cli_git_branch }}
    - ${{ inputs.keg_hub_git_branch }}
    - ${{ inputs.tap_ref }}
    - ${{ inputs.tap_head_ref }}
    - ${{ inputs.tap_alias }}
    - ${{ inputs.repository }}
    - ${{ inputs.command }}
    - ${{ inputs.token }}
    - ${{ inputs.user }}
