name: test
on:
  push:
    branches:
      - master
      - develop

jobs:
  test-build-push:
    runs-on: ubuntu-latest
    name: Build tap image test
    steps:
    - name: Cancel Previous Workflows In Progress
      uses: styfle/cancel-workflow-action@0.9.0
      with:
        access_token: ${{ github.token }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Tap Run Task
      id: tap-run-task
      uses: ./
      with:
        repository: simpleviewinc/tap-visitapps-app
        tap_ref: /ref/heads/deploy-task
        command: keg vaa path
        token: ${{ secrets.GIT_TOKEN }}
    - name: Test output
      id: test-output
      run: echo "Task output = ${{ steps.tap-run-task.outputs.TASK_OUTPUT }}"